apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busy
  name: busy-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
        ether.edgerun.io/function: busy
        type: busy-fn
    spec:
      nodeSelector:
        ether.edgerun.io/zone: zone-c
      containers:
      - image: aicg4t1/busy-python:1.0.2
        imagePullPolicy: Always
        name: busy
        ports:
        -  containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "1000m"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName