apiVersion: v1
kind: Pod
metadata:
  name: request-responder-250-deployment-c
  labels:
    app: request-responder-250
    ether.edgerun.io/function: request_responder_250
    type: request-responder-250-fn
    ether.edgerun.io/zone: zone-c
spec:
  nodeSelector:
    ether.edgerun.io/zone: zone-c
    node-role.kubernetes.io/worker: "true"
  containers:
  - image: aicg4t1/responder:1.0.1
    imagePullPolicy: Always
    name: request-responder
    ports:
    -  containerPort: 8080
    resources:
      requests:
        memory: "250Mi"
        cpu: "1000m"
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName